// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TournamentScheduler.Api.Data;

#nullable disable

namespace TournamentScheduler.Api.Migrations
{
    [DbContext(typeof(TournamentDbContext))]
    partial class TournamentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TournamentScheduler.Api.Models.Cricket.CricketBall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BallInOver")
                        .HasColumnType("int");

                    b.Property<bool>("BattersCrossed")
                        .HasColumnType("bit");

                    b.Property<int>("BowlerId")
                        .HasColumnType("int");

                    b.Property<int>("Byes")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DismissedPlayerId")
                        .HasColumnType("int");

                    b.Property<int?>("FielderId")
                        .HasColumnType("int");

                    b.Property<int>("InningsId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDirectHit")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFreeHit")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNoBall")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWide")
                        .HasColumnType("bit");

                    b.Property<int>("LegByes")
                        .HasColumnType("int");

                    b.Property<int>("NoBallPenalty")
                        .HasColumnType("int");

                    b.Property<int?>("NonStrikerId")
                        .HasColumnType("int");

                    b.Property<int>("OverNumber")
                        .HasColumnType("int");

                    b.Property<int>("PenaltyRuns")
                        .HasColumnType("int");

                    b.Property<int?>("RunOutReceiverId")
                        .HasColumnType("int");

                    b.Property<int>("RunsOffBat")
                        .HasColumnType("int");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("int");

                    b.Property<int>("StrikerId")
                        .HasColumnType("int");

                    b.Property<int?>("WicketType")
                        .HasColumnType("int");

                    b.Property<int>("WideExtraRuns")
                        .HasColumnType("int");

                    b.Property<int>("WidePenalty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InningsId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("CricketBalls");
                });

            modelBuilder.Entity("TournamentScheduler.Api.Models.Cricket.CricketInnings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BallsPerOver")
                        .HasColumnType("int");

                    b.Property<int>("BattingSideSize")
                        .HasColumnType("int");

                    b.Property<int>("BattingTeamId")
                        .HasColumnType("int");

                    b.Property<int>("BattingTeamInningsIndex")
                        .HasColumnType("int");

                    b.Property<string>("BattingTeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BowlingTeamId")
                        .HasColumnType("int");

                    b.Property<string>("BowlingTeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Byes")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CricketMatchId")
                        .HasColumnType("int");

                    b.Property<int?>("CurrentBowlerId")
                        .HasColumnType("int");

                    b.Property<int?>("EndReason")
                        .HasColumnType("int");

                    b.Property<bool>("FreeHitPending")
                        .HasColumnType("bit");

                    b.Property<int>("InningsNumber")
                        .HasColumnType("int");

                    b.Property<bool>("IsFollowOn")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSuperOver")
                        .HasColumnType("bit");

                    b.Property<int>("LegByes")
                        .HasColumnType("int");

                    b.Property<int>("LegalBalls")
                        .HasColumnType("int");

                    b.Property<bool>("LoneBatter")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxOversPerBowler")
                        .HasColumnType("int");

                    b.Property<int>("NoBalls")
                        .HasColumnType("int");

                    b.Property<int?>("NonStrikerId")
                        .HasColumnType("int");

                    b.Property<int?>("OpeningBowlerId")
                        .HasColumnType("int");

                    b.Property<int?>("OpeningNonStrikerId")
                        .HasColumnType("int");

                    b.Property<int?>("OpeningStrikerId")
                        .HasColumnType("int");

                    b.Property<int?>("OversLimit")
                        .HasColumnType("int");

                    b.Property<int>("PenaltyRuns")
                        .HasColumnType("int");

                    b.Property<int?>("PreviousBowlerId")
                        .HasColumnType("int");

                    b.Property<int>("Runs")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("StrikerId")
                        .HasColumnType("int");

                    b.Property<int?>("Target")
                        .HasColumnType("int");

                    b.Property<int>("Wickets")
                        .HasColumnType("int");

                    b.Property<int>("WicketsToEndInnings")
                        .HasColumnType("int");

                    b.Property<int>("Wides")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CricketMatchId", "InningsNumber")
                        .IsUnique();

                    b.ToTable("CricketInnings");
                });

            modelBuilder.Entity("TournamentScheduler.Api.Models.Cricket.CricketInterruption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AtLegalBalls")
                        .HasColumnType("int");

                    b.Property<int>("BallsAllowedAfter")
                        .HasColumnType("int");

                    b.Property<int>("BallsAllowedBefore")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("InningsId")
                        .HasColumnType("int");

                    b.Property<int>("WicketsAtTime")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InningsId");

                    b.ToTable("CricketInterruptions");
                });

            modelBuilder.Entity("TournamentScheduler.Api.Models.Cricket.CricketMatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AwayTeamId")
                        .HasColumnType("int");

                    b.Property<string>("AwayTeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentInningsNumber")
                        .HasColumnType("int");

                    b.Property<bool>("FollowOnEnforced")
                        .HasColumnType("bit");

                    b.Property<int?>("ForfeitWinnerTeamId")
                        .HasColumnType("int");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HomeTeamId")
                        .HasColumnType("int");

                    b.Property<string>("HomeTeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDraw")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNoResult")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTie")
                        .HasColumnType("bit");

                    b.Property<int>("MatchNumber")
                        .HasColumnType("int");

                    b.Property<string>("ResultSummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SavedFixtureId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TossDecision")
                        .HasColumnType("int");

                    b.Property<int?>("TossWinnerTeamId")
                        .HasColumnType("int");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.Property<int?>("WinnerTeamId")
                        .HasColumnType("int");

                    b.Property<bool>("WonByDls")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("SavedFixtureId");

                    b.HasIndex("TournamentId");

                    b.ToTable("CricketMatches");
                });

            modelBuilder.Entity("TournamentScheduler.Api.Models.Cricket.CricketMatchEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CricketMatchId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.Property<int?>("InningsNumber")
                        .HasColumnType("int");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CricketMatchId");

                    b.ToTable("CricketMatchEvents");
                });

            modelBuilder.Entity("TournamentScheduler.Api.Models.Cricket.CricketMatchPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BattingOrder")
                        .HasColumnType("int");

                    b.Property<int>("CricketMatchId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCaptain")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWicketKeeper")
                        .HasColumnType("bit");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SquadStatus")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.HasIndex("CricketMatchId", "PlayerId")
                        .IsUnique();

                    b.ToTable("CricketMatchPlayers");
                });

            modelBuilder.Entity("TournamentScheduler.Api.Models.Cricket.PlayerCricketProfile", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int?>("BattingOrderPreference")
                        .HasColumnType("int");

                    b.Property<int?>("BattingStyle")
                        .HasColumnType("int");

                    b.Property<int?>("BowlingArm")
                        .HasColumnType("int");

                    b.Property<int?>("BowlingType")
                        .HasColumnType("int");

                    b.Property<int>("PrimaryRole")
                        .HasColumnType("int");

                    b.HasKey("PlayerId");

                    b.ToTable("PlayerCricketProfiles");
                });

            modelBuilder.Entity("TournamentScheduler.Api.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AwayScore")
                        .HasColumnType("int");

                    b.Property<int?>("AwayTeamId")
                        .HasColumnType("int");

                    b.Property<string>("AwayTeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentHalf")
                        .HasColumnType("int");

                    b.Property<int>("CurrentMinute")
                        .HasColumnType("int");

                    b.Property<bool>("DrawAllowed")
                        .HasColumnType("bit");

                    b.Property<int>("ExtraMinutesAddedThisHalf")
                        .HasColumnType("int");

                    b.Property<bool>("ExtraTimeAllowed")
                        .HasColumnType("bit");

                    b.Property<int?>("ExtraTimeMinutesPerHalf")
                        .HasColumnType("int");

                    b.Property<int?>("FinalWhistleMinute")
                        .HasColumnType("int");

                    b.Property<int?>("ForfeitWinnerTeamId")
                        .HasColumnType("int");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("HalfStartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("HomeScore")
                        .HasColumnType("int");

                    b.Property<int?>("HomeTeamId")
                        .HasColumnType("int");

                    b.Property<string>("HomeTeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsClockRunning")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPenaltyShootout")
                        .HasColumnType("bit");

                    b.Property<int>("MatchNumber")
                        .HasColumnType("int");

                    b.Property<int?>("MaxPlayersPerSide")
                        .HasColumnType("int");

                    b.Property<int?>("MaxSubstitutions")
                        .HasColumnType("int");

                    b.Property<int?>("MinPlayersPerSide")
                        .HasColumnType("int");

                    b.Property<int?>("MinutesPerHalf")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PausedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("PausedDurationMs")
                        .HasColumnType("bigint");

                    b.Property<int?>("PenaltyAwayScore")
                        .HasColumnType("int");

                    b.Property<int?>("PenaltyHomeScore")
                        .HasColumnType("int");

                    b.Property<int?>("PenaltyTakersPerSide")
                        .HasColumnType("int");

                    b.Property<int?>("PenaltyWinnerTeamId")
                        .HasColumnType("int");

                    b.Property<int>("PeriodState")
                        .HasColumnType("int");

                    b.Property<bool>("RollingSubsAllowed")
                        .HasColumnType("bit");

                    b.Property<int>("SavedFixtureId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("SavedFixtureId");

                    b.HasIndex("TournamentId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("TournamentScheduler.Api.Models.MatchEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<int>("MinuteOfMatch")
                        .HasColumnType("int");

                    b.Property<int?>("PenaltyAwayScoreAfter")
                        .HasColumnType("int");

                    b.Property<int?>("PenaltyHomeScoreAfter")
                        .HasColumnType("int");

                    b.Property<bool?>("PenaltyScored")
                        .HasColumnType("bit");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int?>("RelatedPlayerId")
                        .HasColumnType("int");

                    b.Property<int?>("StoppageMinute")
                        .HasColumnType("int");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.ToTable("MatchEvents");
                });

            modelBuilder.Entity("TournamentScheduler.Api.Models.MatchPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("SquadStatus")
                        .HasColumnType("int");

                    b.Property<bool>("StartedMatch")
                        .HasColumnType("bit");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable("MatchPlayers");
                });

            modelBuilder.Entity("TournamentScheduler.Api.Models.PenaltyKick", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSuddenDeath")
                        .HasColumnType("bit");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("int");

                    b.Property<bool>("Scored")
                        .HasColumnType("bit");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.ToTable("PenaltyKicks");
                });

            modelBuilder.Entity("TournamentScheduler.Api.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("JerseyNumber")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId", "JerseyNumber")
                        .IsUnique()
                        .HasFilter("[JerseyNumber] IS NOT NULL");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("TournamentScheduler.Api.Models.SavedFixture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Away")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AwayTeamId")
                        .HasColumnType("int");

                    b.Property<string>("Home")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HomeTeamId")
                        .HasColumnType("int");

                    b.Property<int>("MatchNumber")
                        .HasColumnType("int");

                    b.Property<int>("Round")
                        .HasColumnType("int");

                    b.Property<int>("SavedGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SavedGroupId");

                    b.ToTable("SavedFixtures");
                });

            modelBuilder.Entity("TournamentScheduler.Api.Models.SavedGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SavedScheduleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SavedScheduleId");

                    b.ToTable("SavedGroups");
                });

            modelBuilder.Entity("TournamentScheduler.Api.Models.SavedSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MatchesPerTeam")
                        .HasColumnType("int");

                    b.Property<int>("TotalMatches")
                        .HasColumnType("int");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId");

                    b.ToTable("SavedSchedules");
                });

            modelBuilder.Entity("TournamentScheduler.Api.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DefaultCaptainPlayerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId", "Name")
                        .IsUnique();

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("TournamentScheduler.Api.Models.Tournament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsStarted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sport")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("TournamentScheduler.Api.Models.Cricket.CricketBall", b =>
                {
                    b.HasOne("TournamentScheduler.Api.Models.Cricket.CricketInnings", "Innings")
                        .WithMany("Balls")
                        .HasForeignKey("InningsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Innings");
                });

            modelBuilder.Entity("TournamentScheduler.Api.Models.Cricket.CricketInnings", b =>
                {
                    b.HasOne("TournamentScheduler.Api.Models.Cricket.CricketMatch", "Match")
                        .WithMany("Innings")
                        .HasForeignKey("CricketMatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("TournamentScheduler.Api.Models.Cricket.CricketInterruption", b =>
                {
                    b.HasOne("TournamentScheduler.Api.Models.Cricket.CricketInnings", "Innings")
                        .WithMany("Interruptions")
                        .HasForeignKey("InningsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Innings");
                });

            modelBuilder.Entity("TournamentScheduler.Api.Models.Cricket.CricketMatch", b =>
                {
                    b.HasOne("TournamentScheduler.Api.Models.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TournamentScheduler.Api.Models.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TournamentScheduler.Api.Models.SavedFixture", "SavedFixture")
                        .WithMany()
                        .HasForeignKey("SavedFixtureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TournamentScheduler.Api.Models.Tournament", "Tournament")
                        .WithMany("CricketMatches")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("TournamentScheduler.Api.Models.Cricket.CricketMatchRules", "Rules", b1 =>
                        {
                            b1.Property<int>("CricketMatchId")
                                .HasColumnType("int");

                            b1.Property<int>("BallType")
                                .HasColumnType("int");

                            b1.Property<int>("BallsPerOver")
                                .HasColumnType("int");

                            b1.Property<bool>("ByesAllowed")
                                .HasColumnType("bit");

                            b1.Property<bool>("DlsEnabled")
                                .HasColumnType("bit");

                            b1.Property<bool>("DrawAllowed")
                                .HasColumnType("bit");

                            b1.Property<int?>("FollowOnMargin")
                                .HasColumnType("int");

                            b1.Property<int>("Format")
                                .HasColumnType("int");

                            b1.Property<bool>("FreeHitAfterNoBall")
                                .HasColumnType("bit");

                            b1.Property<bool>("FreeHitAfterWide")
                                .HasColumnType("bit");

                            b1.Property<int>("InningsPerSide")
                                .HasColumnType("int");

                            b1.Property<bool>("LastManStanding")
                                .HasColumnType("bit");

                            b1.Property<bool>("LbwEnabled")
                                .HasColumnType("bit");

                            b1.Property<bool>("LegByesAllowed")
                                .HasColumnType("bit");

                            b1.Property<int?>("MaxOversPerBowler")
                                .HasColumnType("int");

                            b1.Property<int>("NoBallPenaltyRuns")
                                .HasColumnType("int");

                            b1.Property<int?>("OversPerInnings")
                                .HasColumnType("int");

                            b1.Property<bool>("OverthrowsAllowed")
                                .HasColumnType("bit");

                            b1.Property<bool>("PenaltyRunsAllowed")
                                .HasColumnType("bit");

                            b1.Property<int>("PitchType")
                                .HasColumnType("int");

                            b1.Property<int>("PlayersPerSide")
                                .HasColumnType("int");

                            b1.Property<string>("PowerplayOvers")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("TieResolution")
                                .HasColumnType("int");

                            b1.Property<int>("WidePenaltyRuns")
                                .HasColumnType("int");

                            b1.HasKey("CricketMatchId");

                            b1.ToTable("CricketMatches");

                            b1.WithOwner()
                                .HasForeignKey("CricketMatchId");
                        });

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("Rules")
                        .IsRequired();

                    b.Navigation("SavedFixture");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("TournamentScheduler.Api.Models.Cricket.CricketMatchEvent", b =>
                {
                    b.HasOne("TournamentScheduler.Api.Models.Cricket.CricketMatch", "Match")
                        .WithMany("Events")
                        .HasForeignKey("CricketMatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("TournamentScheduler.Api.Models.Cricket.CricketMatchPlayer", b =>
                {
                    b.HasOne("TournamentScheduler.Api.Models.Cricket.CricketMatch", "Match")
                        .WithMany("Squad")
                        .HasForeignKey("CricketMatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TournamentScheduler.Api.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TournamentScheduler.Api.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("TournamentScheduler.Api.Models.Cricket.PlayerCricketProfile", b =>
                {
                    b.HasOne("TournamentScheduler.Api.Models.Player", "Player")
                        .WithOne("Cricket")
                        .HasForeignKey("TournamentScheduler.Api.Models.Cricket.PlayerCricketProfile", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("TournamentScheduler.Api.Models.Match", b =>
                {
                    b.HasOne("TournamentScheduler.Api.Models.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TournamentScheduler.Api.Models.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TournamentScheduler.Api.Models.SavedFixture", "SavedFixture")
                        .WithMany()
                        .HasForeignKey("SavedFixtureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TournamentScheduler.Api.Models.Tournament", "Tournament")
                        .WithMany("Matches")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("SavedFixture");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("TournamentScheduler.Api.Models.MatchEvent", b =>
                {
                    b.HasOne("TournamentScheduler.Api.Models.Match", "Match")
                        .WithMany("Events")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("TournamentScheduler.Api.Models.MatchPlayer", b =>
                {
                    b.HasOne("TournamentScheduler.Api.Models.Match", "Match")
                        .WithMany("MatchPlayers")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TournamentScheduler.Api.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TournamentScheduler.Api.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("TournamentScheduler.Api.Models.PenaltyKick", b =>
                {
                    b.HasOne("TournamentScheduler.Api.Models.Match", "Match")
                        .WithMany("PenaltyKicks")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("TournamentScheduler.Api.Models.Player", b =>
                {
                    b.HasOne("TournamentScheduler.Api.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("TournamentScheduler.Api.Models.SavedFixture", b =>
                {
                    b.HasOne("TournamentScheduler.Api.Models.SavedGroup", "SavedGroup")
                        .WithMany("Fixtures")
                        .HasForeignKey("SavedGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SavedGroup");
                });

            modelBuilder.Entity("TournamentScheduler.Api.Models.SavedGroup", b =>
                {
                    b.HasOne("TournamentScheduler.Api.Models.SavedSchedule", "SavedSchedule")
                        .WithMany("Groups")
                        .HasForeignKey("SavedScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SavedSchedule");
                });

            modelBuilder.Entity("TournamentScheduler.Api.Models.SavedSchedule", b =>
                {
                    b.HasOne("TournamentScheduler.Api.Models.Tournament", "Tournament")
                        .WithMany("Schedules")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("TournamentScheduler.Api.Models.Team", b =>
                {
                    b.HasOne("TournamentScheduler.Api.Models.Tournament", "Tournament")
                        .WithMany("Teams")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("TournamentScheduler.Api.Models.Cricket.CricketInnings", b =>
                {
                    b.Navigation("Balls");

                    b.Navigation("Interruptions");
                });

            modelBuilder.Entity("TournamentScheduler.Api.Models.Cricket.CricketMatch", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Innings");

                    b.Navigation("Squad");
                });

            modelBuilder.Entity("TournamentScheduler.Api.Models.Match", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("MatchPlayers");

                    b.Navigation("PenaltyKicks");
                });

            modelBuilder.Entity("TournamentScheduler.Api.Models.Player", b =>
                {
                    b.Navigation("Cricket");
                });

            modelBuilder.Entity("TournamentScheduler.Api.Models.SavedGroup", b =>
                {
                    b.Navigation("Fixtures");
                });

            modelBuilder.Entity("TournamentScheduler.Api.Models.SavedSchedule", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("TournamentScheduler.Api.Models.Team", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("TournamentScheduler.Api.Models.Tournament", b =>
                {
                    b.Navigation("CricketMatches");

                    b.Navigation("Matches");

                    b.Navigation("Schedules");

                    b.Navigation("Teams");
                });
#pragma warning restore 612, 618
        }
    }
}
